name = "convergence-explorer"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "convergence-db"
database_id = "e3f335e8-087d-4612-a9f1-ef3e6cce4a3d"
